### PR TITLE
improved overturn documentation and output conventions

### PR DESCRIPTION
**Pull request by hdrake**
See https://github.com/modscripps/mixsea/pull/80#issuecomment-944981646

### CODE REVIEW

**Comment by hdrake** [comment]
The main thing I did was added this info box about the Thorpe scale method. There are also some other minor improvements, including changing the convention for outputting thorpe displacements (by unsorting)

Screen Shot 2021-10-16 at 6 47 39 PM

**Comment by hdrake** [comment]
Note: https://github.com/modscripps/mixsea/commit/8c5b7d57e377975ad3284216e88e8dea887a1002 seems to have also broken the documentation formatting on master, but this Pull Request fixes it.

**Comment by jessecusack** [comment]
Looks great and almost ready to go.

Would you mind running the notebooks from top to bottom with restarted kernel, then clear all the outputs, then commit the result to this PR. That should (hopefully) prevent of some of the jupyter notebook metadata/binary bloat from creeping in.

**Comment by jessecusack** [comment]
In fact, running from top to bottom is not what I used to do... somehow I completely removed execution numbers. I have forgotten how though... this isn't a very big deal though. The figure data is the priority.

**Pull request merged**
