### PR TITLE
function for intermediate profile method

### PR DESCRIPTION
**Pull request by jessecusack**
This goes some way towards fulfilling https://github.com/modscripps/mixsea/issues/13. To completely fulfill it requires a more major rewrite of `eps_overturns` because the function doesn't work without the intermediate profile method.

### CODE REVIEW

**Comment by gunnarvoet** [comment]
Looks great! We should probably think about how the general workflow for the overturn calculation should look like. For input data, there could be a simple option for using temperature instead of density. Maybe another switch for creating an intermediate profile?

**Comment by jessecusack** [comment]
In my opinion, we probably want a 'does everything function' which is essentially what `eps_overturns` is right now. It should take the minimal inputs from a typical CTD profile (S, T, P, lon?, lat?), as well as the Ozmidov to Thorpe scaling alpha, and produce the most basic possible useful output: epsilon and N2. I think it should assume that the inputs have already been cleaned (no NaNs). Like numpy does with many common functions, we could provide a nan_eps_overturns that attempts to deal with NaN values... but it opens up potential problems as to how exactly to deal with NaNs, e.g. interpolate, remove, something else? 

The 'do everything' function would support switches to use T, S or density for detecting overturns.  Switches for different ways of computing N2 and also for different quality control methods (intermediate profile, ratio method, Galbraith & Kelly etc.) and their parameters. I think it should also have a switch for optionally returning diagnostics, which would be a dictionary that could contain things such as Ozmidov scale, Thorpe displacements, overturn boundary indices, flags for which overturns were rejected by which quality control method, etc. etc. anything we thing reasonable.

For this to work smoothly I think we would need to separate the code that detects overturns from the code that does quality control and computes N2. I can have a think about how best to do this...

Does any of that make sense/sound reasonable to you?

**Comment by gunnarvoet** [comment]
Thanks for your thoughts, this does make sense. Yes, I think there should be one function that can be simple to use or be made more complex if the user desires.

I am often annoyed by all the warnings numpy spits out when you do have NaNs in your data. On the other hand, having a clean routine that very predictably does what you expect from it is worth a lot. Having a `nan_eps_overturn` could indeed be a convenient way to provide both, a clean method in `eps_overturn` and a (highly subjective) way of dealing with NaNs.

I definitely like returning only a minimum of results and having additional diagnostics come optional in a dictionary. It just gets so messy when you have 10 output variables. I'm assuming the epsilon output would only have valid overturn regions (based on whatever quality control you selected) and the diagnostics then show you where overturns were rejected? What are the standard outputs we would like to see? Maybe only epsilon to keep it simple?

Separating overturn detection from quality control definitely makes sense. I'm not quite sure how to modularize the quality control checks, since the intermediate profile one is actively involved in the calculation while the others are not. Maybe it means running the overturn detection without intermediate profile as standard and then, if selected, again with an intermediate profile?

**Comment by jessecusack** [comment]
> I'm assuming the epsilon output would only have valid overturn regions (based on whatever quality control you selected) and the diagnostics then show you where overturns were rejected?

Yes that was my thinking.

> What are the standard outputs we would like to see?

Just epsilon and N squared would be my preference. From those outputs the user can calculate K if they want...

> Maybe it means running the overturn detection without intermediate profile as standard and then, if selected, again with an intermediate profile?

Yes, something like that. So long as we don't imagine this toolbox will be use in a truly 'big data' situation or one where numerical speed is a priority.

**Comment by gunnarvoet** [comment]
That sounds all great. To make it really efficient one would probably only do the overturn detection twice if the user asks for extra output. That should be easy to implement later.

Do you want to take a stab at this? I'll think about how to restructure the shear/strain method along these lines, i.e. optional selection of parameters and outputs in addition to a base function.

**Comment by jessecusack** [comment]
Sure, I'll take a stab at it!

**Pull request merged**
